[workspace]
resolver = "2"
members = [
    "project/crates/app-log-print",
    "project/crates/log-core",
    "project/crates/log-proto",
    "project/crates/log-plugin-sdk",
    "project/plugins/inputs/input-file",
    "project/plugins/inputs/input-program",
    "project/plugins/outputs/output-raw",
    "project/plugins/outputs/output-transform",
    "project/plugins/outputs/output-file",
]
exclude = [
    "project/plugins/inputs/input-serial",
    "project/plugins/outputs/output-tui",
    "project/plugins/outputs/output-webui",
]

[workspace.package]
version = "0.1.2"
edition = "2021"
license = "MIT"
rust-version = "1.92"

[workspace.dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
clap = { version = "4", features = ["derive"] }
log-proto = { path = "project/crates/log-proto" }
log-plugin-sdk = { path = "project/crates/log-plugin-sdk" }
