[package]
name = "log-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
log-proto = { path = "../log-proto" }
tokio.workspace = true
serde.workspace = true
bytes.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
