[package]
name = "output-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
log-proto = { path = "../../log-proto" }
log-plugin-sdk = { path = "../../log-plugin-sdk" }
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
