[package]
name = "output-transform"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
log-proto.workspace = true
log-plugin-sdk.workspace = true
io-plugin-util = { path = "../../inputs/io-plugin-util" }
encoding_rs = "0.8"
chardetng = "0.1.17"
regex = "1"
